server:
  port: 8080
logging:
  path: logs
  file: mylog.log
spring:
    application:
      name: myTest
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.101.212:3306/test
      username: root
      password: 123456
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
     - mapper/*
